name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ci-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build
        run: yarn build

      - name: Typecheck
        run: yarn typecheck
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test-ci
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          start: yarn start:mocks
          wait-on: 'http://localhost:8811'
        env:
          PORT: '8811'

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
